const UPDATE_COLOR = 'UPDATE_COLOR';
const TOGGLE_MENU_ITEM = 'TOGGLE_MENU_ITEM';
const UPDATE_STROKE_WIDTH = 'UPDATE_STROKE_WIDTH';

export {
  UPDATE_COLOR,
  TOGGLE_MENU_ITEM,
  UPDATE_STROKE_WIDTH,
};